Reorganize setup

diff --git a/assets/setup b/assets/setup
--- a/assets/setup
+++ b/assets/setup
@@ -2,18 +2,27 @@
 
 set -e
 
-if [ -z ${RUBY_VERSION} ]; then
-    echo "Error! Ruby version not specified!"
-    exit 1
-else
-    echo "Building image with RUBY_VERSION=${RUBY_VERSION}"
-fi
+check_env() {
+    if [ -z ${2} ]; then
+        echo "Error! ${1} not specified!"
+        exit 1
+    else
+        echo "Building image with ${1}=${2}"
+    fi
+}
 
-apt-get update
+check_env 'RUBY_VERSION' ${RUBY_VERSION}
+check_env 'PHANTOM_JS_VERSION' ${PHANTOM_JS_VERSION}
+
+# Prepare system for rbenv and ruby
 apt-get install -y build-essential zlib1g-dev libssl-dev libreadline-dev \
                    libyaml-dev libxml2-dev libxslt-dev libffi-dev        \
                    libmysqlclient-dev                                    \
                    git net-tools openssh-server openssh-client
+
+# Install gitlab stack
+apt-get install -y postgresql libpq-dev redis-server libicu-dev ed cmake \
+                   g++ nodejs libkrb5-dev golang nginx pkg-config
 
 # Install rbenv
 git clone https://github.com/sstephenson/rbenv.git /usr/local/rbenv
@@ -22,38 +31,33 @@ git clone https://github.com/sstephenson/ruby-build.git /usr/local/rbenv/plugins
 cd /usr/local/rbenv/plugins/ruby-build
 ./install.sh
 
-echo "export RBENV_ROOT=\"/usr/local/rbenv\"" >> /etc/rbenvrc
-echo "export PATH=\"\$RBENV_ROOT/bin:\$PATH\"" >> /etc/rbenvrc
-echo "eval \"\$(rbenv init -)\"" >> /etc/rbenvrc
 echo "gem: --no-rdoc --no-ri" >> /etc/skel/.gemrc
 echo "gem: --no-rdoc --no-ri" >> /root/.gemrc
-echo "source /etc/rbenvrc" >> /etc/skel/.bashrc
-echo "source /etc/rbenvrc" >> /root/.bashrc
+echo "source /etc/rbenvrc"    >> /etc/skel/.bashrc
+echo "source /etc/rbenvrc"    >> /root/.bashrc
+echo "export RBENV_ROOT=\"/usr/local/rbenv\""  >> /etc/rbenvrc
+echo "export PATH=\"\$RBENV_ROOT/bin:\$PATH\"" >> /etc/rbenvrc
+echo "eval \"\$(rbenv init -)\""               >> /etc/rbenvrc
 
 export CONFIGURE_OPTS="--disable-install-doc"
 
-# Install ruby
-bash -l -c "source /etc/rbenvrc && rbenv install ${RUBY_VERSION} && rbenv global ${RUBY_VERSION} && gem install bundler"
-addgroup rbenv
-chgrp rbenv -R /usr/local/rbenv
-chmod g+w -R /usr/local/rbenv
-
-# Install gitlab stack
-apt-get install -y postgresql libpq-dev redis-server libicu-dev ed \
-                   cmake g++ nodejs libkrb5-dev golang nginx pkg-config
-
-# Install phantomjs
-export PHANTOM_JS="phantomjs-1.9.8-linux-x86_64"
-cd /tmp
-wget -q "https://bitbucket.org/ariya/phantomjs/downloads/${PHANTOM_JS}.tar.bz2"
-tar -xvjf ${PHANTOM_JS}.tar.bz2
-mv ${PHANTOM_JS} /usr/local/share
-ln -s /usr/local/share/${PHANTOM_JS}/bin/phantomjs /usr/local/bin
-phantomjs --version
-
 # Add development user
+addgroup rbenv
 useradd -d /home/git -m -s /bin/bash -G rbenv git
 adduser git sudo
+
+# Install ruby
+bash -l -c "source /etc/rbenvrc && rbenv install ${RUBY_VERSION} && rbenv global ${RUBY_VERSION} && gem install bundler"
+chgrp rbenv -R /usr/local/rbenv
+chmod g+w   -R /usr/local/rbenv
+
+# Install phantomjs
+cd /tmp
+wget -q "https://bitbucket.org/ariya/phantomjs/downloads/${PHANTOM_JS_VERSION}.tar.bz2"
+tar -xvjf ${PHANTOM_JS_VERSION}.tar.bz2
+mv ${PHANTOM_JS_VERSION} /usr/local/share
+ln -s /usr/local/share/${PHANTOM_JS_VERSION}/bin/phantomjs /usr/local/bin
+phantomjs --version
 
 # Install gems
 sudo -u git bash -l -c "source /etc/rbenvrc; git clone https://gitlab.com/gitlab-org/gitlab-development-kit.git /tmp/gdk; cd /tmp/gdk; make"
